/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CitizensIdRouteImport } from './routes/citizens.$id'
import { Route as EnrollmentIdRouteImport } from './routes/enrollment.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizensIdRoute = CitizensIdRouteImport.update({
  id: '/citizens/$id',
  path: '/citizens/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentIdRoute = EnrollmentIdRouteImport.update({
  id: '/enrollment/$id',
  path: '/enrollment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/citizens/$id': typeof CitizensIdRoute
  '/enrollment/$id': typeof EnrollmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/citizens/$id': typeof CitizensIdRoute
  '/enrollment/$id': typeof EnrollmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/citizens/$id': typeof CitizensIdRoute
  '/enrollment/$id': typeof EnrollmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/citizens/$id' | '/enrollment/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/citizens/$id' | '/enrollment/$id'
  id: '__root__' | '/' | '/login' | '/citizens/$id' | '/enrollment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CitizensIdRoute: typeof CitizensIdRoute
  EnrollmentIdRoute: typeof EnrollmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizens/$id': {
      id: '/citizens/$id'
      path: '/citizens/$id'
      fullPath: '/citizens/$id'
      preLoaderRoute: typeof CitizensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment/$id': {
      id: '/enrollment/$id'
      path: '/enrollment/$id'
      fullPath: '/enrollment/$id'
      preLoaderRoute: typeof EnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CitizensIdRoute: CitizensIdRoute,
  EnrollmentIdRoute: EnrollmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
