/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as DemandeIdRouteImport } from './routes/demande.$id'
import { Route as DossiersIdRouteImport } from './routes/dossiers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandeIdRoute = DemandeIdRouteImport.update({
  id: '/demande/$id',
  path: '/demande/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersIdRoute = DossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/demande/$id': typeof DemandeIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/demande/$id': typeof DemandeIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/demande/$id': typeof DemandeIdRoute
  '/dossiers/$id': typeof DossiersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connexion' | '/demande/$id' | '/dossiers/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connexion' | '/demande/$id' | '/dossiers/$id'
  id: '__root__' | '/' | '/connexion' | '/demande/$id' | '/dossiers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  DemandeIdRoute: typeof DemandeIdRoute
  DossiersIdRoute: typeof DossiersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande/$id': {
      id: '/demande/$id'
      path: '/demande/$id'
      fullPath: '/demande/$id'
      preLoaderRoute: typeof DemandeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers/$id': {
      id: '/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof DossiersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  DemandeIdRoute: DemandeIdRoute,
  DossiersIdRoute: DossiersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
